// Auto-generated by export.py — do not edit directly.
// Last updated: 2026-04-23 15:19 UTC
const EMPLOYER_DATA = [
  {
    "group": "$1,000 one-time grant",
    "label": "BNY Mellon",
    "value": "bny_mellon|1000|seed|seed_grant",
    "note": "newborns of U.S. employees, born 2025–2028",
    "source_url": "https://www.bny.com/corporate/global/en/about-us/newsroom/press-release/bny-joins-us-government-investment-initiative-for-children-expanding-access-to-savings-and-financial-opportunity-for-employees-130454.html"
  },
  {
    "group": "$1,000 + conditional $1,000",
    "label": "IBM",
    "value": "ibm|1000|conditional|seed_grant",
    "note": "+$1,000 if family contributes $4,000+ within 24 months",
    "source_url": "https://atr.org/trumpaccounts/"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "BlackRock",
    "value": "blackrock|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Steak 'n Shake",
    "value": "steak_n_shake|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://www.foxbusiness.com/politics/steak-n-shake-pledges-1k-contributions-trump-accounts-employees-children"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Nvidia",
    "value": "nvidia|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Chipotle",
    "value": "chipotle|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Uber",
    "value": "uber|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Visa",
    "value": "visa|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Citi",
    "value": "citi|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://www.foxbusiness.com/markets/citi-match-federal-governments-1k-trump-account-contributions-employees-children"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Fox Corporation",
    "value": "fox|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://www.foxcorporation.com/news/corp-press-releases/2026/fox-corporation-announces-it-will-match-u-s-governments-1000-contribution-to-trump-accounts-childrens-retirement-program/"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "News Corporation",
    "value": "newscorp|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://thehill.com/homenews/media/5745359-news-fox-corp-matching-federal-contribution-to-trump-accounts/"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Acorns",
    "value": "acorns|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "State Street",
    "value": "statestreet|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "JPMorgan Chase",
    "value": "jpmorgan|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Robinhood",
    "value": "robinhood|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Chime",
    "value": "chime|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "SoFi",
    "value": "sofi|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Charles Schwab",
    "value": "schwab|1000|all|seed_grant",
    "source_url": "https://pressroom.aboutschwab.com/press-releases/press-release/2025/Charles-Schwab-to-Match-U-S--Governments-1000-Contribution-to-Trump-Accounts-for-Employees-Children/default.aspx"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Russell Investments",
    "value": "russell|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Bank of America",
    "value": "bofa|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for all 165,000 U.S. employees with children born 2025-2028. Also offers pretax payroll deductions for employee contributions.",
    "source_url": "https://newsroom.bankofamerica.com/content/newsroom/stories/2026/03/a-letter-to-shareholders-from-chair-and-ceo--brian-moynihan.html"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Coinbase",
    "value": "coinbase|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Empower",
    "value": "empower|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Intel",
    "value": "intel|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Investment Company Institute",
    "value": "ici|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Turning Point USA",
    "value": "tpusa|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Wells Fargo",
    "value": "wellsfargo|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for employees with children born 2025-2028.",
    "source_url": "https://www.bloomberg.com/news/articles/2026-01-28/jpmorgan-bofa-match-workers-1-000-trump-account-contributions"
  },
  {
    "group": "Variable — contact HR",
    "label": "Mastercard",
    "value": "mastercard|0|variable|seed_grant",
    "source_url": "https://www.newsweek.com/list-of-billionaires-banks-and-businesses-contributing-to-trump-accounts-11435860"
  },
  {
    "group": "Variable — contact HR",
    "label": "Comcast",
    "value": "comcast|0|variable|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Dell Technologies",
    "value": "dell_corp|1000|seed|seed_grant",
    "note": "separate from Dell Foundation philanthropic grant",
    "source_url": "https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2025~12~dell-technologies-signs-invest-america-business-pledge-to-support-employee-families.htm"
  },
  {
    "group": "Variable — contact HR",
    "label": "Broadcom",
    "value": "broadcom|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Continental Resources",
    "value": "continental|0|variable|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Charter Communications",
    "value": "charter|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://corporate.charter.com/newsroom/charter-joins-invest-in-america-trump-accounts-initiative"
  },
  {
    "group": "Variable — contact HR",
    "label": "CTIA",
    "value": "ctia|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Block",
    "value": "block|0|variable|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Replit",
    "value": "replit|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for children of Replit employees born 2025-2028.",
    "source_url": "https://x.com/amasad/status/2022024057445904492"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Galaxy Digital",
    "value": "galaxy_digital|1000|seed|seed_grant",
    "note": "newborns of U.S. employees, born 2025–2028",
    "source_url": "https://www.galaxy.com/newsroom/galaxy-to-match-us-governments-contribution-to-trump-accounts"
  },
  {
    "group": "Variable — contact HR",
    "label": "Goldman Sachs",
    "value": "goldman_sachs|0|variable|seed_grant",
    "source_url": "https://investamerica.org/",
    "verified": true
  },
  {
    "group": "$1,500 employer contribution",
    "label": "Vanguard",
    "value": "vanguard|1500|all|seed_grant",
    "note": "Crew members may direct $1,500 well-being benefit to a Trump Account",
    "source_url": "https://corporate.vanguard.com/content/corporatesite/us/en/corp/articles/vanguard-outlines-corporate-support-trump-accounts.html"
  }
];
