// Auto-generated by export.py — do not edit directly.
// Last updated: 2026-05-15 17:56 UTC
const EMPLOYER_DATA = [
  {
    "group": "$1,000 one-time grant",
    "label": "BNY Mellon",
    "value": "bny_mellon|1000|seed|seed_grant",
    "note": "newborns of U.S. employees, born 2025–2028",
    "source_url": "https://www.bny.com/corporate/global/en/about-us/newsroom/press-release/bny-joins-us-government-investment-initiative-for-children-expanding-access-to-savings-and-financial-opportunity-for-employees-130454.html",
    "sort_order": 10,
    "announcement_date": "2025-12-11"
  },
  {
    "group": "$1,000 + conditional $1,000",
    "label": "IBM",
    "value": "ibm|1000|conditional|seed_grant",
    "note": "+$1,000 if family contributes $4,000+ within 24 months",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 20,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "BlackRock",
    "value": "blackrock|1000|all|seed_grant",
    "source_url": "https://www.blackrock.com/corporate/newsroom/press-releases/announcement/blackrocks-continued-support-for-early-wealth-building-initatives",
    "sort_order": 30,
    "announcement_date": "2025-12-17"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Steak 'n Shake",
    "value": "steak_n_shake|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 40,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Invesco",
    "value": "invesco|1000|seed|seed_grant",
    "source_url": "https://www.prnewswire.com/news-releases/invesco-supports-us-government-commitment-to-long-term-investment-opportunity-for-children-302714607.html",
    "sort_order": 50,
    "announcement_date": "2026-03-16"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Nvidia",
    "value": "nvidia|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 50,
    "announcement_date": "2025-06-09"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "S&P Global",
    "value": "spglobal|1000|seed|seed_grant",
    "source_url": "https://www.prnewswire.com/news-releases/sp-global-expands-us-employee-benefits-by-matching-federal-government-contributions-to-child-savings-accounts-302736318.html",
    "sort_order": 51,
    "announcement_date": "2026-04-07"
  },
  {
    "group": "$2,500 one-time grant",
    "label": "Heritage Foundation",
    "value": "heritage|2500|seed|seed_grant",
    "source_url": "https://www.heritage.org/press/heritage-foundation-match-2500-child-employee-trump-accounts",
    "sort_order": 52,
    "announcement_date": "2026-01-30"
  },
  {
    "group": "$2,500 one-time grant",
    "label": "Center for a Free Economy",
    "value": "cfec|2500|seed|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 53
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Brownstein Hyatt Farber Schreck",
    "value": "brownstein|1000|seed|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 54,
    "announcement_date": "2026-03-26"
  },
  {
    "group": "Variable — contact HR",
    "label": "Delta Airlines",
    "value": "delta|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 55,
    "announcement_date": "2026-04-07"
  },
  {
    "group": "Variable — contact HR",
    "label": "iHeartMedia",
    "value": "iheartmedia|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 56
  },
  {
    "group": "Variable — contact HR",
    "label": "WP Engine",
    "value": "wpengine|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 57
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Chipotle",
    "value": "chipotle|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 60,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Uber",
    "value": "uber|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 70,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Visa",
    "value": "visa|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 80,
    "announcement_date": "2025-12-17"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Citi",
    "value": "citi|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://www.foxbusiness.com/markets/citi-match-federal-governments-1k-trump-account-contributions-employees-children",
    "sort_order": 90,
    "announcement_date": "2026-02-05"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Fox Corporation",
    "value": "fox|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://www.foxcorporation.com/news/corp-press-releases/2026/fox-corporation-announces-it-will-match-u-s-governments-1000-contribution-to-trump-accounts-childrens-retirement-program/",
    "sort_order": 100,
    "announcement_date": "2026-02-19"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "News Corporation",
    "value": "newscorp|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://thehill.com/homenews/media/5745359-news-fox-corp-matching-federal-contribution-to-trump-accounts/",
    "sort_order": 110,
    "announcement_date": "2026-02-19"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Acorns",
    "value": "acorns|1000|all|seed_grant",
    "source_url": "https://www.acorns.com/learn/acorns-matches-trump-account-for-employees/",
    "sort_order": 120,
    "announcement_date": "2026-02-04"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "State Street",
    "value": "statestreet|1000|all|seed_grant",
    "source_url": "https://investors.statestreet.com/investor-news-events/press-releases/news-details/2025/State-Street-to-Match-U-S--Treasury-Contributions-to-New-Child-Savings-Accounts/default.aspx",
    "sort_order": 130,
    "announcement_date": "2025-12-18"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "JPMorgan Chase",
    "value": "jpmorgan|1000|all|seed_grant",
    "source_url": "https://www.reuters.com/business/finance/bofa-match-us-governments-pilot-contribution-trump-accounts-memo-says-2026-01-28/",
    "sort_order": 140,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Robinhood",
    "value": "robinhood|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 150,
    "announcement_date": "2025-12-19"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Chime",
    "value": "chime|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 160,
    "announcement_date": "2025-12-17"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "SoFi",
    "value": "sofi|1000|all|seed_grant",
    "source_url": "https://investors.sofi.com/news/news-details/2026/SoFi-to-Match-1000-Federal-Contribution-to-Investment-Accounts-for-Employees-Children/default.aspx",
    "sort_order": 170,
    "announcement_date": "2026-01-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Charles Schwab",
    "value": "schwab|1000|all|seed_grant",
    "source_url": "https://pressroom.aboutschwab.com/press-releases/press-release/2025/Charles-Schwab-to-Match-U-S--Governments-1000-Contribution-to-Trump-Accounts-for-Employees-Children/default.aspx",
    "sort_order": 180,
    "announcement_date": "2025-12-23"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Russell Investments",
    "value": "russell|1000|all|seed_grant",
    "source_url": "https://russellinvestments.com/content/ri/us/en/about-us/newsroom/2026/russell-investments-to-match-us-government-contributions-to-trump-accounts-for-employees-children.html",
    "sort_order": 190,
    "announcement_date": "2026-01-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Bank of America",
    "value": "bofa|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for all 165,000 U.S. employees with children born 2025-2028. Also offers pretax payroll deductions for employee contributions.",
    "source_url": "https://newsroom.bankofamerica.com/content/newsroom/stories/2026/03/a-letter-to-shareholders-from-chair-and-ceo--brian-moynihan.html",
    "sort_order": 200,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Coinbase",
    "value": "coinbase|1000|all|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 210,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Empower",
    "value": "empower|1000|all|seed_grant",
    "source_url": "https://www.empower.com/press-center/empower-launches-1000-benefit-associates-families-through-trump-accounts",
    "sort_order": 220,
    "announcement_date": "2026-02-02"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Intel",
    "value": "intel|1000|all|seed_grant",
    "source_url": "https://newsroom.intel.com/corporate/intel-to-match-federal-contributions-under-trump-accounts-program-for-employees-families",
    "sort_order": 230,
    "announcement_date": "2026-01-27"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Investment Company Institute",
    "value": "ici|1000|all|seed_grant",
    "source_url": "https://www.ici.org/news-release/ici-announces-trump-account-matching-contribution",
    "sort_order": 240,
    "announcement_date": "2026-01-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Turning Point USA",
    "value": "tpusa|1000|all|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 250,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Wells Fargo",
    "value": "wellsfargo|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for employees with children born 2025-2028.",
    "source_url": "https://www.reuters.com/business/finance/bofa-match-us-governments-pilot-contribution-trump-accounts-memo-says-2026-01-28/",
    "sort_order": 260,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "Variable — contact HR",
    "label": "Mastercard",
    "value": "mastercard|0|variable|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 270,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "Variable — contact HR",
    "label": "Comcast",
    "value": "comcast|0|variable|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 280,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Dell Technologies",
    "value": "dell_corp|1000|seed|seed_grant",
    "note": "separate from Dell Foundation philanthropic grant",
    "source_url": "https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2025~12~dell-technologies-signs-invest-america-business-pledge-to-support-employee-families.htm",
    "sort_order": 290,
    "announcement_date": "2025-12-02"
  },
  {
    "group": "Variable — contact HR",
    "label": "Broadcom",
    "value": "broadcom|0|variable|seed_grant",
    "source_url": "https://home.treasury.gov/news/press-releases/sb0374",
    "sort_order": 300,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "Variable — contact HR",
    "label": "Continental Resources",
    "value": "continental|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 310,
    "announcement_date": "2026-02-14"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Charter Communications",
    "value": "charter|1000|seed|seed_grant",
    "note": "children born 2025–2028",
    "source_url": "https://corporate.charter.com/newsroom/charter-joins-invest-in-america-trump-accounts-initiative",
    "sort_order": 320,
    "announcement_date": "2025-07-21"
  },
  {
    "group": "Variable — contact HR",
    "label": "CTIA",
    "value": "ctia|0|variable|seed_grant",
    "source_url": "https://www.prnewswire.com/news-releases/ctia-announces-support-of-trump-accounts-for-employees-302675092.html",
    "sort_order": 330,
    "announcement_date": "2026-01-30"
  },
  {
    "group": "Variable — contact HR",
    "label": "Block",
    "value": "block|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 340,
    "announcement_date": "2026-01-28"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Replit",
    "value": "replit|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for children of Replit employees born 2025-2028.",
    "source_url": "https://x.com/amasad/status/2022024057445904492",
    "sort_order": 350,
    "announcement_date": "2026-02-12"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Galaxy Digital",
    "value": "galaxy_digital|1000|seed|seed_grant",
    "note": "newborns of U.S. employees, born 2025–2028",
    "source_url": "https://www.galaxy.com/newsroom/galaxy-to-match-us-governments-contribution-to-trump-accounts",
    "sort_order": 360,
    "announcement_date": "2026-03-25"
  },
  {
    "group": "Variable — contact HR",
    "label": "Goldman Sachs",
    "value": "goldman_sachs|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 370,
    "announcement_date": "2025-06-09"
  },
  {
    "group": "$1,500 employer contribution",
    "label": "Vanguard",
    "value": "vanguard|1500|all|seed_grant",
    "note": "Crew members may direct $1,500 well-being benefit to a Trump Account",
    "source_url": "https://corporate.vanguard.com/content/corporatesite/us/en/corp/articles/vanguard-outlines-corporate-support-trump-accounts.html",
    "sort_order": 380,
    "announcement_date": "2026-04-06"
  },
  {
    "group": "$2,500 one-time grant",
    "label": "IntraFi",
    "value": "intrafi|2500|seed|seed_grant",
    "note": "Matches $1,000 federal seed + up to $1,500 additional match for employees who contribute; newborns of eligible employees",
    "source_url": "https://www.intrafi.com/press-releases/intrafi-launches-match-for-employee-trump-accounts",
    "sort_order": 390,
    "announcement_date": "2026-04-10"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Nasdaq",
    "value": "nasdaq|1000|all|seed_grant",
    "source_url": "https://www.nasdaq.com/press-release/nasdaq-match-federal-contribution-trump-accounts-employees-children-2026-04-29",
    "sort_order": 410,
    "announcement_date": "2026-04-29"
  },
  {
    "group": "Variable — contact HR",
    "label": "Silver Lake",
    "value": "silver_lake|0|variable|seed_grant",
    "source_url": "https://atr.org/trumpaccounts/",
    "sort_order": 420
  }
];
