// Auto-generated by export.py — do not edit directly.
// Last updated: 2026-03-04 03:30 UTC
const EMPLOYER_DATA = [
  {
    "group": "$2,000 one-time grant",
    "label": "BNY Mellon",
    "value": "bny_mellon|2000|newborn|seed_grant",
    "note": "newborns of U.S. employees"
  },
  {
    "group": "$1,000 + conditional $1,000",
    "label": "IBM",
    "value": "ibm|1000|conditional|seed_grant",
    "note": "+$1,000 if family contributes $4,000+ within 24 months"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "BlackRock",
    "value": "blackrock|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Steak 'n Shake",
    "value": "steak_n_shake|1000|seed|seed_grant",
    "note": "children born 2025–2028"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Nvidia",
    "value": "nvidia|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Chipotle",
    "value": "chipotle|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Uber",
    "value": "uber|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Visa",
    "value": "visa|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Citi",
    "value": "citi|1000|seed|seed_grant",
    "note": "children born 2025–2028"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Fox Corporation",
    "value": "fox|1000|seed|seed_grant",
    "note": "children born 2025–2028"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "News Corporation",
    "value": "newscorp|1000|seed|seed_grant",
    "note": "children born 2025–2028"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Acorns",
    "value": "acorns|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "State Street",
    "value": "statestreet|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "JPMorgan Chase",
    "value": "jpmorgan|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Robinhood",
    "value": "robinhood|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Chime",
    "value": "chime|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "SoFi",
    "value": "sofi|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Charles Schwab",
    "value": "schwab|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Russell Investments",
    "value": "russell|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Bank of America",
    "value": "bofa|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for all 165,000 U.S. employees with children born 2025-2028. Also offers pretax payroll deductions for employee contributions."
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Coinbase",
    "value": "coinbase|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Empower",
    "value": "empower|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Intel",
    "value": "intel|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Investment Company Institute",
    "value": "ici|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Turning Point USA",
    "value": "tpusa|1000|all|seed_grant"
  },
  {
    "group": "$1,000 one-time grant",
    "label": "Wells Fargo",
    "value": "wellsfargo|1000|seed|seed_grant",
    "note": "Matches the $1,000 federal seed for employees with children born 2025-2028."
  },
  {
    "group": "Variable — contact HR",
    "label": "Mastercard",
    "value": "mastercard|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Comcast",
    "value": "comcast|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Dell Technologies",
    "value": "dell_corp|0|variable|seed_grant",
    "note": "separate from Dell Foundation philanthropic grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Broadcom",
    "value": "broadcom|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Continental Resources",
    "value": "continental|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Charter Communications",
    "value": "charter|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "CTIA",
    "value": "ctia|0|variable|seed_grant"
  },
  {
    "group": "Variable — contact HR",
    "label": "Block",
    "value": "block|0|variable|seed_grant"
  }
];
