"""
export.py — Export trump_accounts.db tables to JS files for the frontend.
Run after any DB update:  python3 export.py

Outputs:
  employers.js    — employer seed grant data
  zip_income.js   — ZIP code median income lookup (requires census_import.py first)
"""

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

DB_PATH = Path(__file__).parent / "trump_accounts.db"


def export_employers(conn, timestamp):
    rows = conn.execute(
        """
        SELECT id, name, grant_amount, condition_type, group_label, note, contribution_type, source_url
        FROM   employers
        ORDER  BY sort_order, name
        """
    ).fetchall()

    employers = []
    for r in rows:
        amt = r["grant_amount"] if r["grant_amount"] is not None else 0
        entry = {
            "group": r["group_label"],
            "label": r["name"],
            "value": f"{r['id']}|{amt}|{r['condition_type']}|{r['contribution_type']}",
        }
        if r["note"]:
            entry["note"] = r["note"]
        if r["source_url"]:
            entry["source_url"] = r["source_url"]
        employers.append(entry)

    js = (
        f"// Auto-generated by export.py — do not edit directly.\n"
        f"// Last updated: {timestamp}\n"
        f"const EMPLOYER_DATA = {json.dumps(employers, indent=2, ensure_ascii=False)};\n"
    )
    out = Path(__file__).parent / "employers.js"
    out.write_text(js, encoding="utf-8")
    print(f"✓ employers.js written ({len(employers)} employers)")


def export_zip_income(conn, timestamp):
    # Check if table exists
    exists = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='zip_income'"
    ).fetchone()

    if not exists:
        print("  zip_income table not found — run `python3 census_import.py` first, skipping.")
        return

    rows = conn.execute(
        "SELECT zip, median_income FROM zip_income WHERE median_income IS NOT NULL"
    ).fetchall()

    # Simple dict: {"10001": 75000, ...} for O(1) frontend lookup
    zip_dict = {r["zip"]: r["median_income"] for r in rows}

    # Pull vintage year from DB
    year_row = conn.execute("SELECT year FROM zip_income WHERE year IS NOT NULL LIMIT 1").fetchone()
    vintage_year = year_row["year"] if year_row else "unknown"

    meta = {
        "source": "U.S. Census Bureau",
        "survey": "American Community Survey (ACS) 5-Year Estimates",
        "table": "B19013 — Median Household Income in the Past 12 Months",
        "vintage_year": vintage_year,
        "exported": timestamp,
    }

    js = (
        f"// Auto-generated by export.py — do not edit directly.\n"
        f"// Last updated: {timestamp}\n"
        f"const ZIP_INCOME_META = {json.dumps(meta, indent=2)};\n"
        f"const ZIP_INCOME = {json.dumps(zip_dict, separators=(',', ':'))};\n"
    )
    out = Path(__file__).parent / "zip_income.js"
    out.write_text(js, encoding="utf-8")
    size_kb = out.stat().st_size / 1024
    print(f"✓ zip_income.js written ({len(zip_dict):,} ZIPs, {size_kb:.0f} KB)")


def main():
    if not DB_PATH.exists():
        raise FileNotFoundError("trump_accounts.db not found. Run `python3 seed.py` first.")

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    export_employers(conn, timestamp)
    export_zip_income(conn, timestamp)

    conn.close()


if __name__ == "__main__":
    main()
