"""
export.py — Export trump_accounts.db tables to JS files for the frontend.
Run after any DB update:  python3 export.py

Outputs:
  employers.js    — employer seed grant data
  zip_income.js   — ZIP code median income lookup (requires census_import.py first)
"""

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

DB_PATH = Path(__file__).parent / "trump_accounts.db"


def export_employers(conn, timestamp):
    rows = conn.execute(
        """
        SELECT id, name, grant_amount, condition_type, group_label, note, contribution_type, source_url
        FROM   employers
        ORDER  BY sort_order, name
        """
    ).fetchall()

    employers = []
    for r in rows:
        amt = r["grant_amount"] if r["grant_amount"] is not None else 0
        entry = {
            "group": r["group_label"],
            "label": r["name"],
            "value": f"{r['id']}|{amt}|{r['condition_type']}|{r['contribution_type']}",
        }
        if r["note"]:
            entry["note"] = r["note"]
        if r["source_url"]:
            entry["source_url"] = r["source_url"]
        employers.append(entry)

    js = (
        f"// Auto-generated by export.py — do not edit directly.\n"
        f"// Last updated: {timestamp}\n"
        f"const EMPLOYER_DATA = {json.dumps(employers, indent=2, ensure_ascii=False)};\n"
    )
    out = Path(__file__).parent / "employers.js"
    out.write_text(js, encoding="utf-8")
    print(f"✓ employers.js written ({len(employers)} employers)")


def export_zip_income(conn, timestamp):
    # Check if table exists
    exists = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='zip_income'"
    ).fetchone()

    if not exists:
        print("  zip_income table not found — run `python3 census_import.py` first, skipping.")
        return

    rows = conn.execute(
        "SELECT zip, median_income FROM zip_income WHERE median_income IS NOT NULL"
    ).fetchall()

    # Simple dict: {"10001": 75000, ...} for O(1) frontend lookup
    zip_dict = {r["zip"]: r["median_income"] for r in rows}

    # Pull vintage year from DB
    year_row = conn.execute("SELECT year FROM zip_income WHERE year IS NOT NULL LIMIT 1").fetchone()
    vintage_year = year_row["year"] if year_row else "unknown"

    meta = {
        "source": "U.S. Census Bureau",
        "survey": "American Community Survey (ACS) 5-Year Estimates",
        "table": "B19013 — Median Household Income in the Past 12 Months",
        "vintage_year": vintage_year,
        "exported": timestamp,
    }

    js = (
        f"// Auto-generated by export.py — do not edit directly.\n"
        f"// Last updated: {timestamp}\n"
        f"const ZIP_INCOME_META = {json.dumps(meta, indent=2)};\n"
        f"const ZIP_INCOME = {json.dumps(zip_dict, separators=(',', ':'))};\n"
    )
    out = Path(__file__).parent / "zip_income.js"
    out.write_text(js, encoding="utf-8")
    size_kb = out.stat().st_size / 1024
    print(f"✓ zip_income.js written ({len(zip_dict):,} ZIPs, {size_kb:.0f} KB)")


def export_state_grants(conn, timestamp):
    exists = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='state_grants'"
    ).fetchone()
    if not exists:
        print("  state_grants table not found — skipping.")
        return

    rows = conn.execute(
        """SELECT id, state_code, grantor_name, donor_line, grant_amount, amount_display,
                  req_no_seed, req_has_seed, req_age_max, req_born_year,
                  req_zip_income, income_cap, req_zip_set,
                  req_county_checkbox, county_checkbox_label, county_checkbox_label2,
                  note, source_url, sort_order
           FROM state_grants ORDER BY sort_order, grantor_name"""
    ).fetchall()

    grants = [dict(r) for r in rows]
    js = (
        f"// Auto-generated by export.py — do not edit directly.\n"
        f"// Last updated: {timestamp}\n"
        f"const STATE_GRANTS = {json.dumps(grants, indent=2, ensure_ascii=False)};\n"
    )
    out = Path(__file__).parent / "state_grants.js"
    out.write_text(js, encoding="utf-8")
    print(f"✓ state_grants.js written ({len(grants)} grants)")


def export_state_grants_sql(conn):
    exists = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='state_grants'"
    ).fetchone()
    if not exists:
        print("  state_grants table not found — skipping state_grants_seed.sql.")
        return

    rows = conn.execute(
        """SELECT id, state_code, grantor_name, donor_line, grant_amount, amount_display,
                  req_no_seed, req_has_seed, req_age_max, req_born_year,
                  req_zip_income, income_cap, req_zip_set,
                  req_county_checkbox, county_checkbox_label, county_checkbox_label2,
                  note, source_url, sort_order
           FROM state_grants ORDER BY sort_order, grantor_name"""
    ).fetchall()

    lines = ["DELETE FROM state_grants;"]
    for r in rows:
        vals = ",".join([
            sql_quote(r["id"]), sql_quote(r["state_code"]), sql_quote(r["grantor_name"]),
            sql_quote(r["donor_line"]), str(r["grant_amount"]) if r["grant_amount"] is not None else "NULL",
            sql_quote(r["amount_display"]),
            str(r["req_no_seed"]), str(r["req_has_seed"]),
            str(r["req_age_max"]) if r["req_age_max"] is not None else "NULL",
            str(r["req_born_year"]) if r["req_born_year"] is not None else "NULL",
            str(r["req_zip_income"]),
            str(r["income_cap"]) if r["income_cap"] is not None else "NULL",
            sql_quote(r["req_zip_set"]),
            str(r["req_county_checkbox"]),
            sql_quote(r["county_checkbox_label"]), sql_quote(r["county_checkbox_label2"]),
            sql_quote(r["note"]), sql_quote(r["source_url"]),
            str(r["sort_order"]),
        ])
        lines.append(
            f"INSERT INTO state_grants (id,state_code,grantor_name,donor_line,grant_amount,amount_display,"
            f"req_no_seed,req_has_seed,req_age_max,req_born_year,"
            f"req_zip_income,income_cap,req_zip_set,"
            f"req_county_checkbox,county_checkbox_label,county_checkbox_label2,"
            f"note,source_url,sort_order) VALUES ({vals});"
        )
    Path("state_grants_seed.sql").write_text("\n".join(lines))
    print(f"✓ state_grants_seed.sql written ({len(rows)} grants)")


def sql_quote(v):
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def export_employers_sql(conn):
    rows = conn.execute(
        "SELECT id, name, grant_amount, condition_type, group_label, note, "
        "sort_order, contribution_type, source_url FROM employers ORDER BY sort_order, name"
    ).fetchall()
    lines = ["DELETE FROM employers;"]
    for r in rows:
        amt = r["grant_amount"] if r["grant_amount"] is not None else "NULL"
        lines.append(
            f"INSERT INTO employers (id,name,grant_amount,condition_type,group_label,note,"
            f"sort_order,contribution_type,source_url) VALUES ("
            f"{sql_quote(r['id'])},{sql_quote(r['name'])},{amt},"
            f"{sql_quote(r['condition_type'])},{sql_quote(r['group_label'])},{sql_quote(r['note'])},"
            f"{r['sort_order']},{sql_quote(r['contribution_type'])},{sql_quote(r['source_url'])});"
        )
    Path("employers_seed.sql").write_text("\n".join(lines))
    print(f"✓ employers_seed.sql written ({len(rows)} employers)")


def export_zip_income_sql(conn):
    exists = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='zip_income'"
    ).fetchone()
    if not exists:
        print("  zip_income table not found — skipping zip_income_seed.sql.")
        return
    rows = conn.execute(
        "SELECT zip, median_income, year FROM zip_income WHERE median_income IS NOT NULL"
    ).fetchall()
    lines = ["DELETE FROM zip_income;"]
    for i in range(0, len(rows), 500):
        chunk = rows[i:i + 500]
        vals = ",".join(
            f"({sql_quote(r['zip'])},{r['median_income']},{r['year']})" for r in chunk
        )
        lines.append(f"INSERT INTO zip_income (zip,median_income,year) VALUES {vals};")
    Path("zip_income_seed.sql").write_text("\n".join(lines))
    size_kb = Path("zip_income_seed.sql").stat().st_size / 1024
    print(f"✓ zip_income_seed.sql written ({len(rows):,} ZIPs, {size_kb:.0f} KB)")


def main():
    if not DB_PATH.exists():
        raise FileNotFoundError("trump_accounts.db not found. Run `python3 seed.py` first.")

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    export_employers(conn, timestamp)
    export_zip_income(conn, timestamp)
    export_state_grants(conn, timestamp)
    export_employers_sql(conn)
    export_zip_income_sql(conn)
    export_state_grants_sql(conn)

    conn.close()


if __name__ == "__main__":
    main()
