// Auto-generated by export.py — do not edit directly.
// Last updated: 2026-09-04 10:15 UTC
const ZIP_INCOME_META = {
  "source": "U.S. Census Bureau",
  "survey": "American Community Survey (ACS) 5-Year Estimates",
  "table": "B19013 \u2014 Median Household Income in the Past 12 Months",
  "vintage_year": "unknown",
  "exported": "2026-09-04 10:15 UTC"
};
const ZIP_INCOME = {};
